services:
  nest-app:
    image: node:18.17.0
    container_name: go2-service
    working_dir: /opt/go2-service
    volumes:
      - .:/opt/go2-service
    ports:
      - "3322:3322"
    command: ["npm", "run", "start:prod"]
    environment:
      - NODE_ENV=production
